language: php

php:
  - 5.3
  - 5.4
  - 5.6
  - 5.6
  - 7.0
  - hhvm

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

env:
  - SYMFONY_VERSION=2.7.*

matrix:
  include:
    - php: 5.6
      env: SYMFONY_VERSION=2.3.*
    - php: 5.6
      env: SYMFONY_VERSION=2.8.*@dev
    - php: 5.6
      env: SYMFONY_VERSION=3.0.*@dev
    - php: 5.3
      env: COMPOSER_FLAGS="--prefer-lowest"
  allow_failures:
    - env: SYMFONY_VERSION=3.0.*@dev
    - php: 7.0
    - php: hhvm

before_install:
  - yes '' | pecl -q install -f mongo
  - sh -c 'if [ "${TRAVIS_PHP_VERSION}" != "hhvm" ]; then echo "memory_limit = -1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi;'
  - composer self-update
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;

install: composer update --prefer-source $COMPOSER_FLAGS

script: ./bin/phpunit --coverage-text
