language: php

sudo: false

cache:

  directories:
    - $HOME/.composer/cache

env:

  global:
    - SYMFONY_DEPRECATIONS_HELPER="weak_vendors"
    - PHPUNIT_FLAGS="-v"
    - PHPUNIT_ENABLED="true"
    - SYMFONY_PHPUNIT_VERSION="6.5"
    - PHPCSFIXER_ENABLED="false"
    - COVERALLS_ENABLED="false"

matrix:

  fast_finish: true

  include:

    - php: 7.1
    - php: 7.1
      env:
        - PHPUNIT_ENABLED="false"
        - PHPCSFIXER_ENABLED="true"
    - php: 7.1
      env:
        - SYMFONY_VERSION=4.0.*
        - COMPOSER_FLAGS="--prefer-lowest"
    - php: 7.2
    - php: 7.2
      env: SYMFONY_VERSION=3.4.*
    - php: 7.2
      env: SYMFONY_VERSION=4.0.*
    - php: 7.2
      env:
        - DEPENDENCIES="symfony/phpunit-bridge:^4"
        - COMPOSER_UPDATE_FLAGS="--no-dev"
    - php: 7.2
      env:
        - COVERALLS_ENABLED="true"
        - PHPUNIT_FLAGS="-v --coverage-text --coverage-clover var/build/clover.xml"
    - php: 7.2
      env:
        - SYMFONY_VERSION=dev-master
        - STABILITY=dev
    - php: nightly
      env:
        - SYMFONY_VERSION=4.0.*
        - COMPOSER_FLAGS="--ignore-platform-reqs"

  allow_failures:

    - env:
        - COVERALLS_ENABLED="true"
        - PHPUNIT_FLAGS="-v --coverage-text --coverage-clover var/build/clover.xml"
    - env:
        - SYMFONY_VERSION=dev-master
        - STABILITY=dev
    - php: nightly


before_install:

  - if [[ "$SYMFONY_VERSION" != "" ]]; then
      travis_retry composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update $COMPOSER_FLAGS;
    fi
  - if [[ "$DEPENDENCIES" != "" ]]; then
      travis_retry composer require $DEPENDENCIES --no-update $COMPOSER_FLAGS;
    fi
  - if [[ "$STABILITY" != "" ]]; then
      travis_retry composer config minimum-stability $STABILITY;
    fi
  - if [[ "$COVERALLS_ENABLED" != "true" ]]; then
      phpenv config-rm xdebug.ini || true;
    fi
  - if [[ "$COVERALLS_ENABLED" == "true" ]]; then
      travis_retry composer require --dev satooshi/php-coveralls:^2.0@dev --no-update $COMPOSER_FLAGS;
    fi

install:

  - travis_retry composer update --prefer-dist --no-interaction --no-suggest --no-progress --ansi $COMPOSER_FLAGS $COMPOSER_UPDATE_FLAGS
  - ./vendor/bin/simple-phpunit install

script:

  - if [[ "$PHPUNIT_ENABLED" == "true" ]]; then
      ./vendor/bin/simple-phpunit $PHPUNIT_FLAGS;
    fi
  - if [[ "$PHPCSFIXER_ENABLED" == "true" ]]; then
      vendor/bin/php-cs-fixer --dry-run --diff -vvv fix;
    fi

after_success:

  - if [[ "$PHPUNIT_ENABLED" == "true" && "$COVERALLS_ENABLED" == "true" ]]; then
      ./vendor/bin/php-coveralls -vvv --config .coveralls.yml;
    fi;
